server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}
  cors:
    enabled: false
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]

data:
  local_data_folder: local_data/private_gpt

ui:
  enabled: true
  path: /

llm:
  mode: local

local:
  llm_hf_repo_id: ${LLM_REPO_ID:TheBloke/dolphin-2.2.1-mistral-7B-GGUF}
  llm_hf_model_file: ${LLM_MODEL_FILE:dolphin-2.2.1-mistral-7b.Q5_K_S.gguf}
  embedding_hf_model_name: ${EMBEDDING_MODEL:BAAI/bge-small-en-v1.5}

sagemaker:
  llm_endpoint_name: huggingface-pytorch-tgi-inference-2023-09-25-19-53-32-140
  embedding_endpoint_name: huggingface-pytorch-inference-2023-11-03-07-41-36-479

openai:
  api_key: ${OPENAI_API_KEY:}